### ISSUE TITLE
FATAL: Module scst not found

### ISSUE THREAD

**Issue by Linekio** [ubuntu-pkg/scst#1]
Hi, I installed scst on debian with method described on Readme and i got this error:

```
root@proxmox2:~# service scst status
● scst.service - LSB: SCST - A Generic SCSI Target Subsystem
   Loaded: loaded (/etc/init.d/scst; generated; vendor preset: enabled)
   Active: active (exited) since Thu 2018-08-02 12:14:18 CEST; 43s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3488 ExecStart=/etc/init.d/scst start (code=exited, status=5)
    Tasks: 0 (limit: 4915)
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/scst.service

Aug 02 12:14:18 proxmox2 systemd[1]: Starting LSB: SCST - A Generic SCSI Target Subsystem...
Aug 02 12:14:18 proxmox2 scst[3488]: Loading and configuring SCSTmodprobe: FATAL: Module scst not found in directory /lib/modules/4.15.18-1-pve
Aug 02 12:14:18 proxmox2 scst[3488]: modprobe scst failed.
Aug 02 12:14:18 proxmox2 scst[3488]:  failed!
Aug 02 12:14:18 proxmox2 systemd[1]: Started LSB: SCST - A Generic SCSI Target Subsystem.
```
scst.conf:
```
root@proxmox2:~# cat /etc/scst.conf 
HANDLER dev_tape {
	DEVICE 3:0:1:0
}

TARGET_DRIVER iscsi {
	enabled 1

	TARGET iqn.2010-04.com.urgencias.local:hu-ds2:tape {
		enabled 1
		LUN 1 3:0:1:0
	}
}

```
Any idea ?
Thanks

**Comment by fajarnugraha** [comment]
Did you install `scst-dkms_*` package? What does `dkms status` show?

**Comment by Linekio** [comment]
Yes I did:
```
root@proxmox2:~# dkms status
scst, 3.4.0: added
```

**Comment by fajarnugraha** [comment]
Added means it hasn't been compiled yet. You're probably missing some packages (e.g. linux-headers-generic in ubuntu, not sure what it is in debian)

I can't support debian since I don't use it. You might find better luck asking in debian forums about compiling modules with dkms.

**Comment by Linekio** [comment]
Thanks, I found the solution.
In reality, it's not debian but proxmox (based on debian). The required headers package for my version is "pve-headers-4.15.18-1-pve", but the mk-build-deps command installed pve-headers.4.13.13-3-pve.
Fixed by installing the correct version before.
